version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    environment:
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
  postgres_data:
  pgadmin-data: